### ISSUE TITLE
Dockerize this tool

### ISSUE THREAD

**Issue by 0xflotus** [joanbono/gap#1]
Can you please provide a docker file for this tool?

**Comment by joanbono** [comment]
Of course.

[Here you have the dockerfile](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

GitHub issues are for real issues with the programs developed.

We take our time to write the code and share it with the community, if you have requests like that, please consider donating to the project or even better, submitting a Pull Request.

Thanks
